# Generated by Django 6.0.4 on 2026-04-24 05:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('headline_rank_title', models.CharField(blank=True, max_length=120, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('highest_rating', models.IntegerField(blank=True, null=True)),
                ('contests_count', models.IntegerField(blank=True, null=True)),
                ('solved_count', models.IntegerField(blank=True, null=True)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('external_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='accounts.externalaccount')),
            ],
            options={
                'ordering': ['-captured_at', '-id'],
            },
        ),
    ]
