# Generated by Django 6.0.4 on 2026-06-14 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProfileSnapshot",
        ),
    ]
