# Generated by Django 6.0.4 on 2026-05-10 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('codeforces', 'Codeforces'), ('codechef', 'CodeChef'), ('leetcode', 'LeetCode'), ('atcoder', 'AtCoder'), ('kaggle', 'Kaggle'), ('github', 'GitHub'), ('ctftime', 'CTFtime'), ('tryhackme', 'TryHackMe'), ('hackthebox', 'Hack The Box'), ('devpost', 'Devpost'), ('dorahacks', 'DoraHacks')], max_length=50)),
                ('handle', models.CharField(max_length=255)),
                ('profile_url', models.URLField(blank=True, max_length=500)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['platform'],
                'constraints': [models.UniqueConstraint(fields=('user', 'platform'), name='unique_user_platform_account')],
            },
        ),
    ]
