# Generated by Django 6.0.4 on 2026-05-10 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeforcesStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=100)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('max_rating', models.IntegerField(blank=True, null=True)),
                ('rank', models.CharField(blank=True, max_length=100, null=True)),
                ('max_rank', models.CharField(blank=True, max_length=100, null=True)),
                ('solved_count', models.PositiveIntegerField(default=0)),
                ('attempted_count', models.PositiveIntegerField(default=0)),
                ('accepted_submission_count', models.PositiveIntegerField(default=0)),
                ('contest_count', models.PositiveIntegerField(default=0)),
                ('last_online_at', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('raw_user_info', models.JSONField(blank=True, default=dict)),
                ('raw_rating_history', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='codeforces_stats', to='connectors.platformaccount')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
