# Generated by Django 6.0.4 on 2026-08-15 05:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0002_codeforcesstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeforcesstats',
            name='recent_activity',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='PlatformStatsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('solved_count', models.PositiveIntegerField(default=0)),
                ('contest_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('platform_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_snapshots', to='connectors.platformaccount')),
            ],
            options={
                'ordering': ['-captured_at', '-id'],
                'indexes': [models.Index(fields=['platform_account', '-captured_at'], name='platform_snapshot_time_idx')],
            },
        ),
    ]
