# Generated by Django 6.0.4 on 2026-08-15 08:29

import django.db.models.deletion
from django.db import migrations, models


def backfill_handle_validation(apps, schema_editor):
    PlatformAccount = apps.get_model("connectors", "PlatformAccount")
    accounts = PlatformAccount.objects.filter(
        is_verified=True,
        handle_validated_at__isnull=True,
    )
    for account in accounts.iterator():
        account.handle_validated_at = account.last_synced_at or account.updated_at
        account.save(update_fields=["handle_validated_at"])


def reverse_handle_validation(apps, schema_editor):
    PlatformAccount = apps.get_model("connectors", "PlatformAccount")
    PlatformAccount.objects.update(handle_validated_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0003_codeforcesstats_recent_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformaccount',
            name='handle_validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='ownership_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='last_sync_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            backfill_handle_validation,
            reverse_handle_validation,
        ),
        migrations.CreateModel(
            name='AtCoderStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(default='algorithm', max_length=32)),
                ('current_rating', models.IntegerField(blank=True, null=True)),
                ('max_rating', models.IntegerField(blank=True, null=True)),
                ('rated_contest_count', models.PositiveIntegerField(default=0)),
                ('last_rated_at', models.DateTimeField(blank=True, null=True)),
                ('last_performance', models.IntegerField(blank=True, null=True)),
                ('rating_data_updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atcoder_stats', to='connectors.platformaccount')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformRatingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(choices=[('algorithm', 'Algorithm')], max_length=32)),
                ('external_contest_id', models.CharField(max_length=255)),
                ('contest_name', models.CharField(blank=True, max_length=500, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('performance', models.IntegerField(blank=True, null=True)),
                ('inner_performance', models.IntegerField(blank=True, null=True)),
                ('old_rating', models.IntegerField(blank=True, null=True)),
                ('new_rating', models.IntegerField(blank=True, null=True)),
                ('rating_change', models.IntegerField(blank=True, null=True)),
                ('is_rated', models.BooleanField()),
                ('occurred_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_events', to='connectors.platformaccount')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
                'indexes': [models.Index(fields=['platform_account', 'discipline', '-occurred_at'], name='platform_rating_event_idx')],
                'constraints': [models.UniqueConstraint(fields=('platform_account', 'discipline', 'external_contest_id'), name='unique_platform_rating_event')],
            },
        ),
    ]
