# Generated by Django 6.0.4 on 2026-08-15 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0004_platformaccount_handle_validated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atcoderstats',
            name='accepted_submission_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='atcoderstats',
            name='attempted_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='atcoderstats',
            name='indexed_submission_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='atcoderstats',
            name='solved_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='atcoderstats',
            name='submission_backfill_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atcoderstats',
            name='submission_data_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atcoderstats',
            name='rating_data_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AtCoderSubmissionSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_submission_epoch', models.BigIntegerField(default=0)),
                ('last_submission_id', models.BigIntegerField(default=0)),
                ('backfill_complete', models.BooleanField(default=False)),
                ('submission_data_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atcoder_submission_sync_state', to='connectors.platformaccount')),
            ],
        ),
        migrations.CreateModel(
            name='AtCoderSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_submission_id', models.BigIntegerField()),
                ('external_contest_id', models.CharField(max_length=255)),
                ('external_problem_id', models.CharField(max_length=255)),
                ('verdict', models.CharField(max_length=64)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('submitted_at', models.DateTimeField()),
                ('provider_epoch_second', models.BigIntegerField()),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('code_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atcoder_submissions', to='connectors.platformaccount')),
            ],
            options={
                'ordering': ['-submitted_at', '-external_submission_id'],
                'indexes': [models.Index(fields=['platform_account', '-submitted_at'], name='atcoder_submission_time_idx'), models.Index(fields=['platform_account', 'external_problem_id'], name='atcoder_submission_problem_idx'), models.Index(fields=['platform_account', 'verdict', 'external_problem_id'], name='atcoder_submission_result_idx')],
                'constraints': [models.UniqueConstraint(fields=('platform_account', 'external_submission_id'), name='unique_atcoder_submission')],
            },
        ),
    ]
