# Generated by Django 6.0.4 on 2026-08-15 10:49

import django.db.models.deletion
from django.db import migrations, models


def normalize_existing_atcoder_state(apps, schema_editor):
    SubmissionState = apps.get_model("connectors", "AtCoderSubmissionSyncState")
    Snapshot = apps.get_model("connectors", "PlatformStatsSnapshot")

    SubmissionState.objects.filter(backfill_complete=True).update(
        progress_status="caught_up"
    )
    for snapshot in Snapshot.objects.filter(
        platform_account__platform="atcoder",
        solved_count=0,
    ).iterator():
        metadata = snapshot.metadata if isinstance(snapshot.metadata, dict) else {}
        if metadata.get("submission_stats_complete") is False:
            snapshot.solved_count = None
            snapshot.save(update_fields=["solved_count"])


def restore_non_nullable_snapshot_values(apps, schema_editor):
    Snapshot = apps.get_model("connectors", "PlatformStatsSnapshot")
    Snapshot.objects.filter(solved_count__isnull=True).update(solved_count=0)


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0005_atcoderstats_accepted_submission_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atcodersubmissionsyncstate',
            name='blocked_reason',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='atcodersubmissionsyncstate',
            name='progress_status',
            field=models.CharField(choices=[('backfilling', 'Backfilling'), ('caught_up', 'Caught up'), ('blocked', 'Blocked')], default='backfilling', max_length=16),
        ),
        migrations.AlterField(
            model_name='platformstatssnapshot',
            name='solved_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AtCoderSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_status', models.CharField(choices=[('never', 'Never synchronized'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='never', max_length=16)),
                ('rating_status', models.CharField(choices=[('never', 'Never synchronized'), ('success', 'Success'), ('skipped_fresh', 'Skipped (fresh)'), ('failed', 'Failed'), ('blocked', 'Blocked'), ('disabled', 'Disabled')], default='never', max_length=20)),
                ('rating_error_code', models.CharField(blank=True, max_length=64)),
                ('rating_sync_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('submission_status', models.CharField(choices=[('never', 'Never synchronized'), ('success', 'Success'), ('skipped_fresh', 'Skipped (fresh)'), ('failed', 'Failed'), ('blocked', 'Blocked'), ('disabled', 'Disabled')], default='never', max_length=20)),
                ('submission_error_code', models.CharField(blank=True, max_length=64)),
                ('submission_sync_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atcoder_sync_state', to='connectors.platformaccount')),
            ],
        ),
        migrations.RunPython(
            normalize_existing_atcoder_state,
            restore_non_nullable_snapshot_values,
        ),
    ]
