# Generated by Django 6.0.4 on 2026-09-06 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0006_atcodersubmissionsyncstate_blocked_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformstatssnapshot',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LeetCodeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('school', models.CharField(blank=True, max_length=255, null=True)),
                ('global_problem_ranking', models.PositiveIntegerField(blank=True, null=True)),
                ('reputation', models.PositiveIntegerField(blank=True, null=True)),
                ('solved_total', models.PositiveIntegerField(default=0)),
                ('solved_easy', models.PositiveIntegerField(default=0)),
                ('solved_medium', models.PositiveIntegerField(default=0)),
                ('solved_hard', models.PositiveIntegerField(default=0)),
                ('problem_stats_complete', models.BooleanField(default=False)),
                ('current_contest_rating', models.FloatField(blank=True, null=True)),
                ('attended_contest_count', models.PositiveIntegerField(default=0)),
                ('contest_global_ranking', models.PositiveIntegerField(blank=True, null=True)),
                ('contest_total_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('contest_top_percentage', models.FloatField(blank=True, null=True)),
                ('rating_history', models.JSONField(blank=True, default=list)),
                ('data_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leetcode_stats', to='connectors.platformaccount')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LeetCodeSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('last_successful_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leetcode_sync_state', to='connectors.platformaccount')),
            ],
        ),
    ]
