# Generated by Django 6.0.4 on 2026-09-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0007_alter_platformstatssnapshot_rating_leetcodestats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leetcodesyncstate',
            name='consecutive_failure_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
