# Generated by Django 6.0.4 on 2026-09-15 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0008_leetcode_sync_consecutive_failures'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTFTeamProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_team_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('data_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ctf_team_profile', to='connectors.platformaccount')),
            ],
        ),
        migrations.CreateModel(
            name='CTFtimeSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('last_successful_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=64)),
                ('consecutive_failure_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ctftime_sync_state', to='connectors.platformaccount')),
            ],
        ),
        migrations.CreateModel(
            name='CTFYearlyRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('global_rank', models.IntegerField(blank=True, null=True)),
                ('country_rank', models.IntegerField(blank=True, null=True)),
                ('rating_points', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_rankings', to='connectors.ctfteamprofile')),
            ],
            options={
                'ordering': ['-year'],
                'indexes': [models.Index(fields=['team_profile', 'year'], name='ctf_ranking_team_year_idx')],
                'constraints': [models.UniqueConstraint(fields=('team_profile', 'year'), name='unique_ctf_team_year')],
            },
        ),
    ]
