# Generated by Django 6.0.4 on 2026-06-14 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_create_missing_user_tables"),
        ("dashboard", "0002_delete_profilesnapshot"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="externalaccount",
            name="uniq_user_source_account",
        ),
        migrations.DeleteModel(
            name="ExternalAccount",
        ),
    ]
